actions:
  vundle: vim +PluginClean! +PluginInstall +PluginInstall! +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: true
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop

dotfiles:
  d_bash_config.sh:
    dst: ~/.config/bash/config.sh
    link: true
    src: .config/bash/config.sh
  d_bash_global.sh:
    dst: ~/.config/bash/global.sh
    link: true
    src: .config/bash/global.sh
  d_bash_local.sh:
    dst: ~/.config/bash/local.sh
    link: false
    src: .config/bash/local.sh
  d_bash_shared.sh:
    dst: ~/.config/bash/shared.sh
    link: true
    src: .config/bash/shared.sh
  d_zsh_config.sh:
    dst: ~/.config/zsh/config.sh
    link: true
    src: .config/zsh/config.sh
  d_zsh_global.sh:
    dst: ~/.config/zsh/global.sh
    link: true
    src: .config/zsh/global.sh
  d_tmux_plugins_tpm:
    dst: ~/.tmux/plugins/tpm
    link: true
    src: .tmux/plugins/tpm
  d_vim:
    dst: ~/.vim
    link: true
    src: .vim
  f_fzf_preview.sh:
    dst: ~/bin/fzf_preview.sh
    link: true
    src: bin/fzf_preview.sh
  f_replace.py:
    dst: ~/bin/replace.py
    link: true
    src: bin/replace.py
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: .gitconfig
  f_htoprc:
    dst: ~/.config/htop/htoprc
    link: true
    src: .config/htop/htoprc
  f_ipython_default:
    dst: ~/.ipython/profile_default/startup/00_default.py
    link: true
    src: .ipython/00_default.py
  f_keras_json:
    dst: ~/.keras/keras.json
    link: true
    src: .keras/keras.json
  f_rprofile:
    dst: ~/.Rprofile
    link: true
    src: .Rprofile
  f_screenrc:
    dst: ~/.screenrc
    link: true
    src: .screenrc
  f_sync_configs.sh:
    dst: ~/bin/sync_configs.sh
    link: true
    src: bin/sync_configs.sh
  f_abspath.py:
    dst: ~/bin/abspath.py
    link: true
    src: bin/abspath.py
  f_rm_confirm.py:
    dst: ~/bin/rm_confirm.py
    link: true
    src: bin/rm_confirm.py
  f_tmux_conf:
    dst: ~/.tmux.conf
    link: true
    src: .tmux.conf
  f_tmux_sessions_default_conf:
    dst: ~/.tmux/sessions/default.conf
    link: true
    src: .tmux/sessions/default.conf
  f_vimrc:
    dst: ~/.vimrc
    link: true
    src: .vim/.vimrc
    actions:
    - vundle

profiles:
  base:
    dotfiles:
    - d_bash_config.sh
    - d_bash_global.sh
    - d_bash_local.sh
    - d_bash_shared.sh
    - d_zsh_config.sh
    - d_zsh_global.sh
    - d_tmux_plugins_tpm
    - d_vim
    - f_fzf_preview.sh
    - f_gitconfig
    - f_htoprc
    - f_ipython_default
    - f_keras_json
    - f_rprofile
    - f_sync_configs.sh
    - f_abspath.py
    - f_rm_confirm.py
    - f_rprofile
    - f_screenrc
    - f_tmux_conf
    - f_tmux_sessions_default_conf
    - f_vimrc
